# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 996fb539e2ea5d6cf4c4baf694d122aa1dd409e8cccc87f41cea348d8b0de3d0bb23eed0c87254ec0158308c7e571b14c4e09c6637f864178efcef75c3e92b41

test:
  secret_key_base: 483fb631d50f364cbfce26c075cf60bd207c630114afcf29cda3a9f2a227d3339c21db52797d2ce906c7c9bbc3705b971dc9678808710c819148ee048f2f05ff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
